Dal nodo: 16-Slim

# Definire l'argomento di costruzione per la filiale
Arg Branch = beta-2

# Installa Git, Python e Pip
Esegui aggiornamenti APT-get && \
    Apt-get install -y git python3 python3-pip && \
    PIP3 Installa richieste && \
    RM -rf/var/lib/apt/elents/*

Workdir /app

# Clona il repository e il checkout specificato Branch
Esegui Git Clone https://github.com/mcoy88f/omg-premium-tv.git . && \
    GIT Checkout $ {Branch}

# Installa dipendenze
Esegui l'installazione NPM

# Crea directory per script di Python e playlist generate
Esegui mkdir -p /app /temp && \
    CHMOD 777 /APP /TEMP
Esegui Chmod 777 /app



# Esporre la porta (usi abbracciati 7860)
ESPORRE 7860

# Imposta le variabili di ambiente essenziali per abbracciare il viso
Porta Env=7860
Ospite Env=0.0.0.0

# Start the application
CMD ["node", "index.js"]
